### ISSUE TITLE
Kørselshistorik - hent metrics fra prometheus

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#11]
```[tasklist]
### Tasks
- [ ] Aftale adgang fra node-red container til prometheus API med KIT
- [ ] Design HTTP API request - https://prometheus.io/docs/prometheus/latest/querying/api/
- [ ] Forlæng storage TSDP https://stackoverflow.com/questions/59298811/increasing-prometheus-storage-retention
```

Kørselshistorik objekt:

```
{
    "startDate": $startDate,
    "endDate": endDate,
    "processedReceipts": [],
    "currentStep": {},
    "stepHistory": [],
    "userName": ""
}
```

steps og states:

```
"steps":
    [
        {
            "title": "initialization",
            "id": 0,
            "state": {},
            "lastResult": null
        },
        {
            "title": "extract-worklet",
            "id": 1,
            "state": {},
            "lastResult": null
        },
        {
            "title": "data-split",
            "id": 2,
            "state": {},
            "lastResult": null
        },
        {
            "title": "extract-kp",
            "id": 3,
            "state": {},
            "lastResult": null
        },
        {
            "title": "transform",
            "id": 4,
            "state": {},
            "lastResult": null
        },
        {
            "title": "load",
            "id": 5,
            "state": {},
            "lastResult": null
        }
    ],

    "states":
    [
        {
            "title": "idle",
            "id": 0,
            "result": ["ready", "completed"]
        },
        
        {
            "title": "running",
            "id": 1,
            "result": "busy"
        },

        {
            "title": "unavailable",
            "id": 2,
            "result": "no response"
        }
    ]
```
