### ISSUE TITLE
Deployment af v2.0

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#114]
```[tasklist]
### Tasks
- [x] Add sealed secrets
- [x] Deploy API-service KP update
- [x] Sikr max-connections på MariaDB ikke skaber problemer
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/96
```
