### ISSUE TITLE
Refactoring af Main-flow i forbindelse med MariaDB implementation

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#15]
```[tasklist]
### Tasks
- [x] Slet unødvendig data undervejs i flow.
- [x] Klargør hvor nødvendigt.
- [x] Saml / opdel nodes hvor det giver mening.
- [x] Gør løsning så generisk som mulig.
- [x] Lav standard for HTTP requests i web.
- [x] Implementer MariaDB
```
