### ISSUE TITLE
Udstil metrics til prometheus

### ISSUE THREAD

**Issue by st-randers** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#72]
```[tasklist]
### Tasks
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/87
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/86
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/33
```

Der skal udstilles metrics til prometheus i fodprojektet.

Metrics kan både være kørsler, men også endpoint status (hvorvidt datakilder er live etc.).

Metrics object kan evt. blive oprettet når en kørsel startes, og samme metric objekt opdateres derefter løbende under kørslen (status) / når sagsbehandler arkiverer fakturaer (receipts archived).

**Comment by st-randers** [comment]
Lukker da den ikke er relevant for projekt.
