### ISSUE TITLE
Løskoblet dataindsamling

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#75]
```[tasklist]
### Tasks
- [ ] Research form engines til dataindsamling @jmk-randers
- [ ] Opsætning af containerized udvikler miljø med løskoblet komponent @jmk-randers
- [ ] Definer use-cases til test og prototyper
```
