### ISSUE TITLE
Automatisk beregning af tilskud til fodterapi v.2.0

### ISSUE THREAD

**Issue by ghost** [Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi#77]
```[tasklist]
### Todo (Need to have)
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/96
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/97
- [x] Opdatering af Sygesikring Danmarks prisaftaler
- [x] Opdatering af prisaftaler for 2025
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/113
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/114
- [ ] Opdater dokumentation (mangler ENV vars mv.)
```

```[tasklist]
### Enhancements (Nice to have)
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/21
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/69
- [x] Mulighed for at genstarte robotten hvis KP dataindlæsning mislykkedes
```

```[tasklist]
### Løst
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/78
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/76
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/91
- [x] Implementér forenklet UI baseret på generic-web-ui repo
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/15
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/100
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/99
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/107
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/105
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/102
- [x] Hjælp-side
```

```[tasklist]
### Parkeret
- [ ] https://github.com/Randers-Kommune-Digitalisering/auto-tilskudsberegning-fodterapi/issues/72
```

**Comment by st-randers** [comment]
Mangler deployment og test på prototypes.

**Comment by st-randers** [comment]
Brugerstyring samt Hjælp side mangler implementering. Herefter kan applikationen testes på prototypes.

**Comment by st-randers** [comment]
Afventer at Borgerservice er klar til at teste v2. Herunder mangler
- Adgangsstyring til udvalgte brugere
- Prisaftaler for 2024
- Opdatering af Sygesikring Danmarks tilskudssatser
